### ISSUE TITLE
Build failed.

### ISSUE THREAD

**Issue by cem2ran** [jorishermans/dartforcetodo#1]
I git cloned, pub get and then pub build, resulting in the following build error:

<pre>
[Info from Dart2JS]:
Compiling dartforcetodo|bin/server.dart...
[Warning from Dart2JS on dartforcetodo|bin/server.dart]:
packages/uuid/uuid.dart:1:9:
Duplicated library name 'Uuid'.
library Uuid;
        ^^^^
[Warning from Dart2JS on dartforcetodo|bin/server.dart]:
packages/uuid/uuid_server.dart:1:9:
Duplicated library name 'Uuid'.
library Uuid;
        ^^^^
[Error from Dart2JS on dartforcetodo|bin/server.dart]:
packages/force/force_serverside.dart:11:8:
Can't read 'package:force_it/force_it.dart' (Could not find asset force_it|lib/force_it.dart.).
import 'package:force_it/force_it.dart';
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Info from Dart2JS]:
Took 0:00:02.848639 to compile dartforcetodo|bin/server.dart.
Build failed.
</pre>

**Comment by jorishermans** [comment]
I fixed it, this was because of the name change of 'force_it' to wired.

So if you could test this again?
